/*
SEAN MADE THIS.
https://plus.google.com/u/0/+SeanYentheHumansperson

This is where the dictionary is stored.
*/
var dict=[
["is am are equals be","se[noun]"],
["exist existence","se",true],
["should recommend recommendation tip","ute[infinitive]",true],
["warn","inute[infinitive]",true],
["can ability able","pote[infinitive]",true],
["must rule guideline required","opore[infinitive]",true],
["i me we us","ek"], /* pretty sure it wouldn't detect the capital I */
["you","tu"],
["eyo/pronoun it he she him her they them","id"],
["eyo/properNounIndicator","don"],
["eyo/abbreviationIndicator","donet"],
["eyo/pronounVerb","ase"],
["that","ka"],
["what","ke"],
["this","ki"],
["one thing -body","ko"],
["all every","ku"],
["some any","kuo"],
["zero 0 no without","nin 0"],
["one 1","un 1"],
["two 2","dos 2"],
["three 3","tris 3"],
["four 4","kat 4"],
["five 5","kin 5"],
["six 6","sek 6"],
["seven 7","sep 7"],
["eight 8","okt 8"],
["nine 9","non 9"],
["eyo/numberToNounForm","-o"],
["eyo/sequentialNumberSuffix","-us"],
["eyo/inverseMeaning in- un-","in-"],
["eyo/verbException not","no-"],
["since because","kon"],
["but except","sed"],
["and","a +"],
["of","e ~"],
["to","i _"],
["or","o /~"],
["eyo/pastTensePrefix","u-"],
["eyo/futureTensePrefix","ua-"],
["eyo/participleSuffix","-a"],
["eyo/verbSuffix","-e"],
["eyo/infinitiveSuffix","-i"],
["eyo/sharedWordNounSuffix","-o"],
["eyo/sharedWordAdjSuffix","-u"],
["eyo/sharedWordAdvSuffix","-uo"],
["same","en"],
["more plus positive yes true","es"],
["most","est"],
["same","inen"],
["less minus negative no false","ines"],
["least","inest"],
]
