/*
SEAN MADE THIS.
https://plus.google.com/u/0/+SeanYentheHumansperson

This is where the dictionary is stored.
*/
var dict=[
["is am are equals be","se [noun]"],
["exist existence","se",true],
["should recommend recommendation tip","ute [infinitive]",true],
["warn","inute [infinitive]",true],
["can ability able","pote [infinitive]",true],
["must rule guideline required","opore [infinitive]",true],
["I me we us","ek"],
["you","tu"],
["eyo/pronoun it he she him her they them","id"],
["eyo/properNounIndicator","don"],
["eyo/abbreviationIndicator","donet"],
["eyo/pronounVerb","ase"],
["that (pronoun) those the","ka"],
["what","ke"],
["this these the","ki"],
["one thing -body","ko"],
["all every","ku"],
["some any","kuo"],
["zero 0 no without","nin 0",""],
["one 1 a an","un 1",""],
["two 2","dos 2",""],
["three 3","tris 3",""],
["four 4","kat 4",""],
["five 5","kin 5",""],
["six 6","sek 6",""],
["seven 7","sep 7",""],
["eight 8","okt 8",""],
["nine 9","non 9",""],
["eyo/decimalPoint . point","ren .",""],
["eyo/ordinalNumberSuffix -st -nd -rd -th","-us"],
["eyo/invertMeaning in- un-","in-"],
["eyo/verbException not","no-"],
["since because","kon"],
["but except","sed"],
["and","a +"],
["of","e ~"],
["to","i _"],
["or","o /"],
["eyo/pastTensePrefix","u-"],
["eyo/futureTensePrefix","ua-"],
["eyo/participleSuffix","-a"],
["eyo/verbSuffix","-e"],
["eyo/infinitiveSuffix","-i"],
["eyo/sharedWordNounSuffix eyo/numberToNounForm","-o"],
["eyo/sharedWordAdjSuffix","-u"],
["eyo/sharedWordAdvSuffix","-uo"],
["same","en"],
["more plus positive yes true +","es +"],
["most","est"],
["different","inen"],
["less minus negative no false -","ines -",""],
["least","inest"],
["in on at within (for time)","on"],
["in on at within (for location)","at"],
["in on at (other uses) within (the guidelines)","in"],
["inside","int"],
["outside","inint"],
["with including using in","kun"],
["without","inkun"],
["by","per"],
["for","inkun"],
["before","ant"],
["after","inant"],
["as","ut"],
["that (subordinating conjunction)","utit"],
["though although","tan"],
["have possess own possession","ape [thing]",true],
["salute greet salutation greeting","saute [thing]",true],
["hi hello hey sup wassup hai","satu"],
["bye bai goodbye bye-bye GODBEWITHYOU","tunorti"],
["die death","norte",true],
["live life","inorte",true],
["world","orpis"],
["number","nuner"],
["apology","apoiat"],
["create make creation","kre [creation]",true],
["-ize","kre-"],
["thank appreciate appreciation","danke [thing]",true],
["speak talk communicate statement","dise",true],
["say state","dise [phrase]"],
["use useful","usue",true],
["hate resent dislike hatred resentment","ode [thing]", true],
["like love prefer preference","inode [thing]",true],
["human boy girl person","onin"],
["accept allow acceptance","asipe [thing]",true],
["reject prevent preventation","inasipe [thing]",true],
["fatten fat","pinue [thing]",true],
["starve skinny thin","inpinue [thing]",true],
["city","ursan"],
["period time","tep"],
["come arrive return destination arrival present","dene",true],
["leave depart departure absent","indene",true],
["house","diat"],
["hope expect wish desire dream optimism hopeful optimistic hopefully","kupe [dependent clause/thing]",true],
["pessimism","inkupo"],
["pessimistic","inkupu"],
["name surname","nonin"],
["eyo/familyName","inonin"],
["-er","-or"],
["lift elevate raise rise","iate [object]"],
["drop fall","iniate"],
["locaton area place","iokus"],
["public","pupik"],
["private","inpupik"],
["embassy","iatit"],
["work job business diligent hard-working hard difficult","ope",true],
["relax easy","inope",true],
["only","sot"],
["build construct structure","konste",true],
["destroy destruction","konste",true],
["child","pur"],
["parent","inpur"],
["when once","kanod"],
["meter","neter"],
["radius","radid"],
["present announce appear show report welcome anouncement apparent visible apparently","nare [thing]",true],
["hide invisible","inare [thing]",true],
["activate activation active","kreksite",true],
["deactivate deactivation inactive","inkreksite",true],
["if","si"],
["watch read","iege [entertainment object]"],
["set configure customize layout","pose",true],
["dismantle","inpose",true],
["pessimistic","inkupu"],
["tinker test experiment study learn","nese [thing]",true],
["go","ae"],
["stay stand","inae"],
["trust faith","iduse [thing]",true],
["doubt distrust","iniduse [thing]",true],
["thin","tenut"],
["thick","intenut"],
["apple","apon"],
["do act action","akte",true],
["try attempt","tende",true],
["know knowledge smart wise intelligent knowingly","ske [thing]",true],
["dumb stupid","insku"],
["keep detain retain hold trap","kuste [thing]"],
["rid clear free","inkuste[thing]"],
["storm","tenepat"],
["snow","nik"],
["mountain hill","kois"],
["night","nokt"],
["day daytime","inokt"],
["light glow white (relatively)","une",true],
["small (relatively)","parut"],
["right (morally)","rait"],
["wrong (morally)","ron"],
["good do good (relatively)","aitsokuraite",true],
["bad do bad (relatively)","kukusoitaite",true],
["mark cue sign","nark"],
["foot","pes"],
["hand","nan"],
["kingdom country state","renon"],
["king queen monarch ruler leader emperor","rek"],
["wail cry (yell) yelp howl","uuate",true],
["wind","entun"],
["like (adjective) similar","sik"],
["whirl twirl swirl twist spiral","spire",true],
["see sight","de [thing]",true],
["blind illusion deception","inde [thing]",true],
["-able","ad-"],
["always","senap"],
["feel feeling","sente",true],
["now","nunk"],
["away","eun"],
["turn rotate rotation","rurse",true],
["slam close shut","kaude"],
["door","ostid"],
["care concern","kure",true],
["rage anger angry","ire",true],
["never","nank"],
["forever","inank"],
["annoy bother annoyance","iakese",true],
["distance","spat"],
["fear","tinor"],
["control rule command reign","enpe [thing]",true],
["catch capture","kapte",true],
["miss","inkapte"],
["limit end","tern"],
["through across","tran"],
["free independent","iper"],
["sky","kait"],
["cry (of sadness)","kane"],
["cry (of happiness)","inkane"],
["power energy","pis"],
["air","aer"],
["ground earth land","teran"],
["flurry","tunute"],
["freeze ice cold chilly frigid icy","durate",true],
["burn fire hot warm","indurate",true],
["fractal","raktai"],
["soul","anin"],
["think thought thoughtful thoughtfully","pute",true],
["blast","iatus"],
["crystal","kristait"],
["sun","sois"],
["perfect","perekt"],
["school","skuas"],
["argue disagree enemy opponent","akue",true],
["agree ally team","inakue",true],
["mean signify","dike"],
["donut","donut"],
["unite join unify together","sine",true],
["separate separation","insine",true],
["tree","ardet"],
["piece part","part"],
["day (twenty-four hours)","diat"],
["year","anot"],
["age","aet"],
["bread","pan"],
["word","sern"],
["attract appeal interest","konpe",true],
["bore boredom","inkonpe",true],
["island","insud"],
["luck fortune","ortun"],
];
