/*
SEAN MADE THIS.
https://plus.google.com/u/0/+SeanYentheHumansperson

This is where the dictionary is stored.
*/
var dict=[
["is am are equals be","se [noun]"],
["exist existence","se",true],
["should recommend recommendation tip","ute [infinitive]",true],
["warn","inute [infinitive]",true],
["can ability able","pote [infinitive]",true],
["must rule guideline required","opore [infinitive]",true],
["I me we us","ek"],
["you","tu"],
["eyo/pronoun it he she him her they them","id"],
["eyo/properNounIndicator","don"],
["eyo/abbreviationIndicator","donet"],
["eyo/pronounVerb","ase"],
["that (pronoun) the","ka"],
["what the","ke"],
["this","ki"],
["one thing -body","ko"],
["all every","ku"],
["some any","kuo"],
["zero 0 no without","nin 0"],
["one 1 a an","un 1"],
["two 2","dos 2"],
["three 3","tris 3"],
["four 4","kat 4"],
["five 5","kin 5"],
["six 6","sek 6"],
["seven 7","sep 7"],
["eight 8","okt 8"],
["nine 9","non 9"],
["eyo/numberToNounForm","-o"],
["eyo/sequentialNumberSuffix","-us"],
["eyo/invertMeaning in- un-","in-"],
["eyo/verbException not","no-"],
["since because","kon"],
["but except","sed"],
["and","a +"],
["of","e ~"],
["to","i _"],
["or","o /~"],
["eyo/pastTensePrefix","u-"],
["eyo/futureTensePrefix","ua-"],
["eyo/participleSuffix","-a"],
["eyo/verbSuffix","-e"],
["eyo/infinitiveSuffix","-i"],
["eyo/sharedWordNounSuffix","-o"],
["eyo/sharedWordAdjSuffix","-u"],
["eyo/sharedWordAdvSuffix","-uo"],
["same","en"],
["more plus positive yes true","es"],
["most","est"],
["different","inen"],
["less minus negative no false","ines"],
["least","inest"],
["in on at within (for time)","on"],
["in on at within (for location)","at"],
["in on at (other uses) within (the guidelines)","in"],
["inside","int"],
["outside","inint"],
["with including using in","kun"],
["without","inkun"],
["by","per"],
["for","inkun"],
["before","ant"],
["after","inant"],
["as","ut"],
["that (subordinating conjunction)","utit"],
["though although","tan"],
["have possess own possession","ape [thing]",true],
["salute greet salutation greeting","saute [thing]",true],
["hi","satu"],
["bye","tunorti"],
["die death","norte",true],
["live life","inorte",true],
["world","orbis"],
["number","nuner"],
["apology","apoiat"],
["create make creation","kre [creation]",true],
["-ize","kre-"],
["thank appreciate appreciation","danke [thing]",true],
["speak talk communicate statement","dise",true],
["say state","dise [phrase]"],
["use useful","usue",true],
["hate resent dislike hatred resentment","ode [thing]", true],
["like love prefer preference","inode [thing]",true],
["human boy girl person","onin"],
["accept allow acceptance","asipe [thing]",true],
["reject prevent preventation","inasipe [thing]",true],
["fatten fat","pinue [thing]",true],
["starve skinny thin","inpinue [thing]",true],
["city","ursan"],
["period time","tep"],
["come arrive return destination","dene",true],
["leave","indene",true],
]
